### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by elandorr** [mattmag/RedEye#2]
Thank you for making this scheme! I like the idea. We need more than the infinite variations of blinding or hard to read, trendy, dark themes.

Some suggestions:
- md support
Headers are treated as comments for instance.
- The highlight_line could use more contrast as well.

Here some inspiration, similar unusual colors: https://packagecontrol.io/packages/industrial-coding-theme. Unfortunately not maintained. (apparently some things changed with v4, the about dialog is unreadable, etc)

**Comment by mattmag** [comment]
Happy that you liked it! And thank you for the suggestions, I'll add markdown support to my next rounds of changes.  I remember struggling with the highlight_line and was never fully satisfied, I'll revisit it and play with the contrast level.

That industrial theme is good - If I had found that first I might not have made the RedEye scheme - or at least put it off for a lot longer 😆. It may inspire me to make some alternate/variations on the redeye theme down the road too.

**Comment by mattmag** [comment]
Fixed via fbccfe18c20da9831d31866c371e843c3b4781b5, fc34ad7bf611265bae8df46588330ca52f421282, and c2d02c3223c1a29e961ce09f4dd5ef573fcff3bd
